# Generated by Django 4.2.5 on 2023-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_feature_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
