# Generated by Django 4.2.3 on 2023-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="department",
            field=models.CharField(
                choices=[
                    ("Backend", "backend"),
                    ("Frontend", "frontend"),
                    ("Network", "network"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
