# Generated by Django 4.2.5 on 2023-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_feature_course"),
        ("courses", "0002_alter_course_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subscriptions",
            field=models.ManyToManyField(
                related_name="courses", to="pricing.subscription"
            ),
        ),
    ]
