# Generated by Django 4.2.5 on 2023-12-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='profile',
        ),
    ]
