# Generated by Django 4.2.5 on 2023-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
