# Generated by Django 4.2.5 on 2023-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
    ]
