# Generated by Django 4.2.3 on 2023-11-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="profile",
        ),
    ]
